name: CI Image

on:
  push:
    branches:
      - master

env:
  ARGOCD_BASE_IMAGE: argoproj/argocd
  ARGOCD_BASE_IMAGE_VERSION: v2.0.1

  IMAGE_REGISTRY: ghcr.io
jobs:
  build:
    name: Build, tag and push
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Set image repository
        run: |
          # Workaround if your Github username/org has uppercase characters which are not allowed in Docker image names
          echo "IMAGE_REPOSITORY=$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
                 --build-arg ARGOCD_BASE_IMAGE=${ARGOCD_BASE_IMAGE} \
                 --build-arg ARGOCD_BASE_IMAGE_VERSION=${ARGOCD_BASE_IMAGE_VERSION} \
                 -t ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${{ github.sha }} .

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.34.0
        id: tag_action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Set image version
        run: |
          tag=${{ steps.tag_action.outputs.tag }}
          echo "IMAGE_VERSION=${tag:1}" >> $GITHUB_ENV

      - name: Tag Docker image
        run: |
          docker tag ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${{ github.sha }} \
                     ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${IMAGE_VERSION}
          docker tag ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${{ github.sha }} \
                     ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:latest

      - name: Log into Docker registry
        run: echo '${{ secrets.GHCR_PAT }}' | docker login ${IMAGE_REGISTRY} -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: |
          docker push ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:${IMAGE_VERSION}
          docker push ${IMAGE_REGISTRY}/${IMAGE_REPOSITORY}:latest

      - name: Notify slack
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          author_name: Image pushed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
