name: CI Image

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  ARGOCD_BASE_IMAGE: argoproj/argocd
  ARGOCD_BASE_IMAGE_VERSION: v2.2.3
  IMAGE_REGISTRY: ghcr.io
jobs:
  build_test_image:
    name: Build and test image
    runs-on: ubuntu-latest
    if: "(!contains(github.event.head_commit.message, 'ci-skip')) && (github.event_name == 'pull_request')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set image repository
        run: |
          # Workaround if your Github username/org has uppercase characters which are not allowed in Docker image names
          echo "IMAGE_REPOSITORY=$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            ARGOCD_BASE_IMAGE=${{ env.ARGOCD_BASE_IMAGE }}
            ARGOCD_BASE_IMAGE_VERSION=${{ env.ARGOCD_BASE_IMAGE_VERSION }}
          tags: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:${{ github.sha }}
          platforms: linux/amd64
          push: false

  build_push_image:
    name: Build and push image
    runs-on: ubuntu-latest
    if: "(!contains(github.event.head_commit.message, 'ci-skip')) && (github.event_name == 'push')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.37.0
        id: tag_action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Set image repository and version
        run: |
          # Workaround if your Github username/org has uppercase characters which are not allowed in Docker image names
          echo "IMAGE_REPOSITORY=$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          
          tag=${{ steps.tag_action.outputs.tag }}
          echo "IMAGE_VERSION=${tag:1}" >> $GITHUB_ENV

      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            ARGOCD_BASE_IMAGE=${{ env.ARGOCD_BASE_IMAGE }}
            ARGOCD_BASE_IMAGE_VERSION=${{ env.ARGOCD_BASE_IMAGE_VERSION }}
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REGISTRY}}/${{ env.IMAGE_REPOSITORY }}:${{ env.IMAGE_VERSION }}
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REGISTRY}}/${{ env.IMAGE_REPOSITORY }}:latest
          platforms: linux/amd64
          push: true

      - name: Notify slack
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          author_name: Image pushed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
